# Generated by Django 5.1.3 on 2024-11-24 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
