# Generated by Django 5.1.3 on 2024-12-07 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_delete_task'),
        ('todos', '0003_todos_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
    ]
